### PR TITLE
Scrum master work

### PR DESCRIPTION
**Pull request by Joshuapmb**
Final branch merging

### CODE REVIEW

**Comment by JamesRobb03** [comment]
Nice work scrum master :)

**Comment by JamesGit1** [comment]
Nice one scrum buddy!

**Review by JesseChan23 — APPROVED** [review]
Well done It is perfect

**Comment by lukedawe** [comment]
A fantastic final commit from a fantastic scrum master

**Review by lukedawe — COMMENTED** [review]
A fantastic final commit from a fantastic scrum master

**Review by JamesRobb03 — COMMENTED** [review]
I hate you all!

**Comment by fincharry27** [comment]
not sure about this....

**Review by fincharry27 — COMMENTED** [review]
yeah i think im really happy about this well done joshy

**Pull request merged**
