### PR TITLE
Quote submission and theme addition is fully functional and looks ama…

### PR DESCRIPTION
**Pull request by fincharry27**
…zing

### CODE REVIEW

**Comment by lukedawe** [comment]
This is some wonderful work

**Comment by JamesGit1** [comment]
That looks ideal!

**Comment by fincharry27** [comment]
HI guys you're really making me blush with all these compliments!

**Comment by fincharry27** [comment]
**What changed**

- The submission of highlighted quotes is now fully functional
- The submission of new themes is fully functional
- All data is correctly submitted to the database for further analysis

**How to use**

- Highlight a quote within the quote editor page and add information against it
- Press submit and consult data base for confirmation

**Pull request merged**
